(function () {
  "use strict";
  var csrf = document.querySelector('meta[name="template-studio-csrf"]').content;
  var draft = null;
  var problem = document.getElementById("creator-problem"), module = document.getElementById("creator-module"), error = document.getElementById("creator-error"), modal = document.getElementById("creator-modal");
  function showError(message) { error.textContent = message || ""; error.hidden = !message; }
  async function request(url, method, body) { var options={method:method||"GET",headers:{}}; if(method&&method!=="GET"){options.headers={"Content-Type":"application/json","X-Template-Studio-CSRF":csrf};options.body=JSON.stringify(body||{});} var response=await fetch(url,options),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||"Не удалось обработать шаблон.");return data; }
  function showDraft(value) { draft=value; document.getElementById("creator-json").value=JSON.stringify(value.generated_json,null,2);document.getElementById("creator-family").textContent="Семейство: "+(value.generated_json.family||"не определено");document.getElementById("creator-status").textContent=value.validation_report.passed?"Validation passed":"Validation failed";var validation=document.getElementById("creator-validation");validation.innerHTML="";(value.validation_report.checks||[]).forEach(function(check){var p=document.createElement("p");p.className=check.passed?"studio-pass":"studio-fail";p.textContent=(check.passed?"✓ ":"× ")+check.message;validation.appendChild(p);});var previews=document.getElementById("creator-previews");previews.innerHTML="";(value.preview_results||[]).forEach(function(item){var article=document.createElement("article"),title=document.createElement("strong"),text=document.createElement("p"),details=document.createElement("pre");article.className="studio-preview";title.textContent="seed "+item.seed;text.textContent=item.rendered_problem;details.textContent="parameters: "+JSON.stringify(item.parameters)+"\nderived: "+JSON.stringify(item.derived_values)+"\nanswer: "+JSON.stringify(item.answer);article.append(title,text,details);previews.appendChild(article);});document.getElementById("creator-warnings").textContent=(value.generated_json.warnings||[]).join("\n")||"Нет предупреждений.";document.getElementById("creator-activate").disabled=!value.validation_report.passed||!!value.generated_json.activation_blocked;modal.showModal(); }
  document.getElementById("creator-generate").addEventListener("click",async function(){showError("");try{showError("Создаётся JSON-шаблон…");var data=await request("/api/template-creator/generate","POST",{problem_text:problem.value,module_id:module.value});showError("");showDraft(data.draft);}catch(e){showError(e.message);}});
  document.getElementById("creator-regenerate").addEventListener("click",async function(){try{showDraft((await request("/api/template-creator/"+encodeURIComponent(draft.draft_id)+"/regenerate","POST",{})).draft);}catch(e){showError(e.message);}});
  document.getElementById("creator-validate").addEventListener("click",async function(){try{showDraft((await request("/api/template-creator/"+encodeURIComponent(draft.draft_id)+"/validate","POST",{})).draft);}catch(e){showError(e.message);}});
  document.getElementById("creator-activate").addEventListener("click",async function(){try{showDraft((await request("/api/template-creator/"+encodeURIComponent(draft.draft_id)+"/activate","POST",{})).draft);}catch(e){showError(e.message);}});
  document.getElementById("creator-delete").addEventListener("click",async function(){if(!window.confirm("Удалить этот generated draft?"))return;try{await request("/api/template-creator/"+encodeURIComponent(draft.draft_id),"DELETE",{confirmed:true});modal.close();draft=null;}catch(e){showError(e.message);}});
  document.getElementById("creator-copy").addEventListener("click",function(){navigator.clipboard.writeText(document.getElementById("creator-json").value).catch(function(){showError("Не удалось скопировать JSON.");});});
  document.getElementById("creator-close").addEventListener("click",function(){modal.close();});
  request("/api/template-creator/modules").then(function(data){(data.modules||[]).forEach(function(item){var option=document.createElement("option");option.value=item.module_id;option.textContent=item.display_name;module.appendChild(option);});}).catch(function(e){showError(e.message);});
})();
